### ISSUE TITLE
PMI Normalization

### ISSUE THREAD

**Issue by Yupei-Du** [dhfbk/hate-speech-artifacts#3]
Hi, 

Thanks for the great work and code. I have a question about the implementation of PMI normalization. 

In the paper, the equation seems to perform min-max normalization before logarithm, 
<img width="260" alt="image" src="https://user-images.githubusercontent.com/24927616/206683669-48799dfd-9bcb-4bd0-baf2-ca555f6dd3c0.png">.

However in the code, the logarithm seems to be [performed](https://github.com/dhfbk/hate-speech-artifacts/blob/9e587266783c2733669a69c4826922129b0083c6/scripts/3.compute-contributions.py#L142) before max-min normalization: 
```python
pmi_scores = np.log2(pmi_scores)
pmi_scores[pmi_scores < 0.0] = 0.0
pmi_normalized = min_max_normalization(pmi_scores)
```
These two different operations will give different scale of the scores (first log then normalize actually treat all tokens with smaller-than-one PMI values as the same --- 0). I was wondering whether I got it wrong? Could you remind me which one I should adopt if I want to perform similar analyses on my own data? 

Thanks, 
Yupei

**Comment by alanramponi** [comment]
Hi Yupei,

Thank you for your interest in our work! I just checked both the code and the equation, and I confirm that there is a mismatch: the logarithm of the PMI values should be performed **before** min-max normalization, as implemented in our code.

Thanks a lot for pointing this out, we will ask for a minor correction in our paper!

Bests,

Alan

**Comment by Yupei-Du** [comment]
Hi Alan, 

Thanks for the reply and help. Nice to know the specific operation to try out on my own data ;)

Yupei
